### ISSUE TITLE
Doesn't build with catch-3.0.1

### ISSUE THREAD

**Issue by yurivict** [fizyr/estd#13]
```
/usr/ports/devel/estd/work/estd-0.6.4/test/main.cpp:30:10: fatal error: 'catch2/catch.hpp' file not found
#include <catch2/catch.hpp>
         ^~~~~~~~~~~~~~~~~~
```

catch-3.0.1 doesn't install ```catch2/catch.hpp``` any more.

**Comment by de-vri-es** [comment]
Thanks for reporting this. A PR for compatibility with Catch2 v3 would be more than welcome!

**Comment by yurivict** [comment]
Sorry, I am only a port maintainer and don't have resources for PRs.

**Comment by de-vri-es** [comment]
Fair enough. Fixed in 4d83a7b5782fae54c5b250d0c9d64de9e1446070 :)

**Comment by de-vri-es** [comment]
Closing, but please let me know if you still have problems building with Catch2 version 3.x.
